load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "scanner",
    srcs = ["Scanner.cpp"],
    hdrs = ["Scanner.h"],
    deps = [
        "//src/Types:types"
    ],
)